# .travis.yml file
language: node_js
node_js:
  - "node"
  - "8"
  - "9"
services:
  - mongodb
install:
  - npm install
deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
script:
  - npm test
